import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState, type FormEvent } from "react";
import { Edit3, FileText, Headphones, Layers, LogOut, Plus, Quote, Tags, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CoverField, RichTextEditor } from "@/components/admin/RichTextEditor";
import { getAdminContent, getAdminStatus, loginAdmin, logoutAdmin, saveCategory, deleteCategory, saveArticle, deleteArticle, saveEpisode, deleteEpisode, saveTestimonial, deleteTestimonial, saveService } from "@/lib/content.functions";


type AdminData = Awaited<ReturnType<typeof getAdminContent>>;
const episodeFields = [
  { name: "title", placeholder: "Título" }, { name: "description", placeholder: "Descrição" },
  { name: "cover_url", placeholder: "URL da capa" }, { name: "youtube_url", placeholder: "YouTube" },
  { name: "spotify_url", placeholder: "Spotify" }, { name: "soundcloud_url", placeholder: "SoundCloud" },
  { name: "youtube_music_url", placeholder: "YouTube Music" }, { name: "amazon_music_url", placeholder: "Amazon Music" },
  { name: "apple_music_url", placeholder: "Apple Music" }, { name: "episode_number", placeholder: "Número do episódio" },
];
export const Route=createFileRoute("/admin")({head:()=>({meta:[{title:"Painel — Viviane Brito"},{name:"description",content:"Área administrativa privada."},{name:"robots",content:"noindex,nofollow"},{property:"og:title",content:"Painel — Viviane Brito"},{property:"og:description",content:"Área administrativa privada."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Admin});
 function Admin(){const statusFn=useServerFn(getAdminStatus),login=useServerFn(loginAdmin),logout=useServerFn(logoutAdmin),getData=useServerFn(getAdminContent);const [authed,setAuthed]=useState<boolean|null>(null),[data,setData]=useState<AdminData|null>(null),[error,setError]=useState("");const [tab,setTab]=useState("articles");const refresh=async()=>{try{const result=await getData();if(!result.authorized){setData(null);setAuthed(false);setError("Sessão expirada. Entre novamente.");return}setData(result)}catch{setData(null);setAuthed(false);setError("Não foi possível carregar o painel. Entre novamente.")}};useEffect(()=>{statusFn().then(async s=>{setAuthed(s.admin);if(s.admin)await refresh()}).catch(()=>setAuthed(false))},[]);
if(authed===null)return <div className="grid min-h-screen place-items-center">Carregando…</div>;if(!authed)return <main className="grid min-h-screen place-items-center bg-secondary p-6"><form className="w-full max-w-sm rounded-lg border bg-background p-8 shadow-xl" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await login({data:{username:String(f.get('username')),password:String(f.get('password'))}});if(r.ok){setAuthed(true);await refresh()}else setError("Usuário ou senha inválidos.")}}><p className="eyebrow text-primary">Área privada</p><h1 className="mt-3 font-display text-4xl">Painel Viviane Brito</h1><input className="field mt-8" name="username" defaultValue="admin" aria-label="Usuário"/><input className="field mt-3" name="password" type="password" placeholder="Senha" aria-label="Senha"/>{error&&<p className="mt-3 text-sm text-destructive">{error}</p>}<Button className="mt-5 w-full" type="submit">Entrar</Button><p className="mt-4 text-xs text-muted-foreground">Por segurança, troque a senha inicial antes de publicar o site.</p></form></main>;
if(!data)return <div className="grid min-h-screen place-items-center">Carregando conteúdo…</div>;
const tabs=[['articles','Artigos',FileText],['categories','Categorias',Tags],['episodes','Podcasts',Headphones],['testimonials','Depoimentos',Quote],['services','Páginas de serviços',Layers]] as const;
return <main className="min-h-screen bg-secondary"><header className="sticky top-0 z-20 border-b bg-background/90 px-5 py-4 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="font-display text-2xl">Viviane Brito</p><p className="text-xs text-muted-foreground">Gestão de conteúdo</p></div><Button variant="outline" onClick={async()=>{await logout();setAuthed(false)}}><LogOut/>Sair</Button></div></header><div className="mx-auto max-w-7xl px-5 py-8"><div className="mb-8 flex gap-2 overflow-x-auto">{tabs.map(([id,label,Icon])=><Button key={id} variant={tab===id?'default':'outline'} onClick={()=>setTab(id)}><Icon/>{label}</Button>)}</div>{tab==='categories'&&<Categories data={data} refresh={refresh}/>} {tab==='articles'&&<ArticlesAdmin data={data} refresh={refresh}/>} {tab==='episodes'&&<EpisodesAdmin data={data} refresh={refresh}/>} {tab==='testimonials'&&<TestimonialsAdmin data={data} refresh={refresh}/>} {tab==='services'&&<ServicesAdmin data={data} refresh={refresh}/>}</div></main>}
function TestimonialsAdmin({data,refresh}:{data:AdminData;refresh:()=>Promise<void>}){const save=useServerFn(saveTestimonial),del=useServerFn(deleteTestimonial);const [editing,setEditing]=useState<Record<string,any>|null>(null);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await save({data:{id:editing?.['id'],name:String(f.get('name')),context:String(f.get('context')||''),quote:String(f.get('quote')||''),content:String(f.get('content')||''),cover_url:String(f.get('cover_url')||'')||null,order_index:Number(f.get('order_index'))||0,published:f.get('published')==='on'}});setEditing(null);await refresh()}
return <section><div className="flex justify-between"><h2 className="admin-title">Depoimentos</h2><Button onClick={()=>setEditing({})}><Plus/>Novo depoimento</Button></div><p className="mb-4 text-sm text-muted-foreground">Cada depoimento tem sua própria página. Os textos atuais são temporários.</p>{editing&&<form className="admin-form" onSubmit={submit}><input className="field" name="name" defaultValue={editing['name']??''} placeholder="Nome de quem depõe" required/><input className="field" name="context" defaultValue={editing['context']??''} placeholder="Contexto do trabalho (não clínico)"/><input className="field" name="quote" defaultValue={editing['quote']??''} placeholder="Frase em destaque"/><input className="field" name="order_index" type="number" defaultValue={editing['order_index']??0} placeholder="Ordem"/><CoverField name="cover_url" defaultValue={editing['cover_url']}/><RichTextEditor name="content" defaultValue={editing['content']}/><label className="flex items-center gap-2"><input type="checkbox" name="published" defaultChecked={Boolean(editing['published'])}/> Publicado</label><div className="flex gap-2"><Button type="submit">Salvar</Button><Button variant="outline" type="button" onClick={()=>setEditing(null)}>Cancelar</Button></div></form>}<div className="mt-6 grid gap-3">{data.testimonials.map(t=><div className="admin-row" key={t.id}><div><b>{t.name}</b><p className="text-xs text-muted-foreground">/depoimentos/{t.slug} · {t.published?'Publicado':'Rascunho'}</p></div><div className="flex"><Button variant="ghost" size="icon" onClick={()=>setEditing(t)}><Edit3/></Button><Button variant="ghost" size="icon" onClick={async()=>{if(confirm('Excluir este depoimento?')){await del({data:{id:t.id}});await refresh()}}}><Trash2/></Button></div></div>)}</div></section>}
function ServicesAdmin({data,refresh}:{data:AdminData;refresh:()=>Promise<void>}){const save=useServerFn(saveService);const [editing,setEditing]=useState<Record<string,any>|null>(null);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await save({data:{id:editing?.['id'],slug:String(f.get('slug')),title:String(f.get('title')),subtitle:String(f.get('subtitle')||''),intro:String(f.get('intro')||''),content:String(f.get('content')||''),cover_url:String(f.get('cover_url')||'')||null,cta_label:String(f.get('cta_label')||'Vamos conversar'),order_index:Number(f.get('order_index'))||0,published:f.get('published')==='on'}});setEditing(null);await refresh()}
return <section><div className="flex justify-between"><h2 className="admin-title">Páginas de serviços</h2><Button onClick={()=>setEditing({})}><Plus/>Nova página</Button></div><p className="mb-4 text-sm text-muted-foreground">Páginas Para Grupos, Para Pessoas e Para Empresas. Os textos atuais são temporários.</p>{editing&&<form className="admin-form" onSubmit={submit}><input className="field" name="title" defaultValue={editing['title']??''} placeholder="Título" required/><input className="field" name="slug" defaultValue={editing['slug']??''} placeholder="Endereço (ex.: grupos)" required/><input className="field" name="subtitle" defaultValue={editing['subtitle']??''} placeholder="Subtítulo"/><input className="field" name="intro" defaultValue={editing['intro']??''} placeholder="Frase de abertura"/><input className="field" name="cta_label" defaultValue={editing['cta_label']??''} placeholder="Texto do convite"/><input className="field" name="order_index" type="number" defaultValue={editing['order_index']??0} placeholder="Ordem"/><CoverField name="cover_url" defaultValue={editing['cover_url']}/><RichTextEditor name="content" defaultValue={editing['content']}/><label className="flex items-center gap-2"><input type="checkbox" name="published" defaultChecked={editing['published']!==false}/> Publicado</label><div className="flex gap-2"><Button type="submit">Salvar</Button><Button variant="outline" type="button" onClick={()=>setEditing(null)}>Cancelar</Button></div></form>}<div className="mt-6 grid gap-3">{data.services.map(s=><div className="admin-row" key={s.id}><div><b>{s.title}</b><p className="text-xs text-muted-foreground">/servicos/{s.slug} · {s.published?'Publicado':'Rascunho'}</p></div><Button variant="ghost" size="icon" onClick={()=>setEditing(s)}><Edit3/></Button></div>)}</div></section>}

function Categories({data,refresh}:{data:AdminData;refresh:()=>Promise<void>}){const save=useServerFn(saveCategory),del=useServerFn(deleteCategory);return <section><h2 className="admin-title">Categorias</h2><form className="mb-8 flex max-w-lg gap-3" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await save({data:{name:String(f.get('name'))}});e.currentTarget.reset();await refresh()}}><input className="field" name="name" placeholder="Nova categoria" required/><Button type="submit"><Plus/>Criar</Button></form><div className="grid gap-3">{data.categories.map(c=><div key={c.id} className="admin-row"><span>{c.name}</span><Button variant="ghost" size="icon" onClick={async()=>{if(confirm('Excluir esta categoria?')){try{await del({data:{id:c.id}});await refresh()}catch(e){alert(e instanceof Error?e.message:'Não foi possível excluir')}}}}><Trash2/></Button></div>)}</div></section>}
function ArticlesAdmin({data,refresh}:{data:AdminData;refresh:()=>Promise<void>}){const save=useServerFn(saveArticle),del=useServerFn(deleteArticle);const [editing,setEditing]=useState<any>(null);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await save({data:{id:editing?.id,title:String(f.get('title')),excerpt:String(f.get('excerpt')),content:String(f.get('content')),cover_url:String(f.get('cover_url'))||null,category_id:String(f.get('category_id'))||null,published:f.get('published')==='on'}});setEditing(null);await refresh()}return <section><div className="flex justify-between"><h2 className="admin-title">Artigos</h2><Button onClick={()=>setEditing({})}><Plus/>Novo artigo</Button></div>{editing&&<form className="admin-form" onSubmit={submit}><input className="field" name="title" defaultValue={editing.title} placeholder="Título" required/><input className="field" name="excerpt" defaultValue={editing.excerpt} placeholder="Resumo"/><CoverField name="cover_url" defaultValue={editing.cover_url}/><select className="field" name="category_id" defaultValue={editing.category_id||''}><option value="">Sem categoria</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><RichTextEditor name="content" defaultValue={editing.content}/><label className="flex items-center gap-2"><input type="checkbox" name="published" defaultChecked={editing.published}/> Publicado</label><div className="flex gap-2"><Button type="submit">Salvar</Button><Button variant="outline" type="button" onClick={()=>setEditing(null)}>Cancelar</Button></div></form>}<div className="mt-6 grid gap-3">{data.articles.map(a=><div className="admin-row" key={a.id}><div><b>{a.title}</b><p className="text-xs text-muted-foreground">{a.published?'Publicado':'Rascunho'}</p></div><div className="flex"><Button variant="ghost" size="icon" onClick={()=>setEditing(a)}><Edit3/></Button><Button variant="ghost" size="icon" onClick={async()=>{if(confirm('Excluir este artigo?')){await del({data:{id:a.id}});await refresh()}}}><Trash2/></Button></div></div>)}</div></section>}
function EpisodesAdmin({data,refresh}:{data:AdminData;refresh:()=>Promise<void>}){const save=useServerFn(saveEpisode),del=useServerFn(deleteEpisode);const [editing,setEditing]=useState<Record<string, any>|null>(null);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const val=(n:string)=>String(f.get(n)||'')||null;await save({data:{id:editing?.['id'],title:String(f.get('title')),description:String(f.get('description')),cover_url:val('cover_url'),youtube_url:val('youtube_url'),spotify_url:val('spotify_url'),soundcloud_url:val('soundcloud_url'),youtube_music_url:val('youtube_music_url'),amazon_music_url:val('amazon_music_url'),apple_music_url:val('apple_music_url'),episode_number:Number(f.get('episode_number'))||null,published:f.get('published')==='on'}});setEditing(null);await refresh()}return <section><div className="flex justify-between"><h2 className="admin-title">Episódios</h2><Button onClick={()=>setEditing({})}><Plus/>Novo episódio</Button></div>{editing&&<form className="admin-form" onSubmit={submit}>{episodeFields.map(({name,placeholder})=><input key={name} className="field" name={name} defaultValue={editing[name] ?? ""} placeholder={placeholder} required={name==='title'}/>) }<label className="flex items-center gap-2"><input type="checkbox" name="published" defaultChecked={Boolean(editing['published'])}/> Publicado</label><div className="flex gap-2"><Button type="submit">Salvar</Button><Button variant="outline" type="button" onClick={()=>setEditing(null)}>Cancelar</Button></div></form>}<div className="mt-6 grid gap-3">{data.episodes.map(e=><div className="admin-row" key={e.id}><div><b>{e.title}</b><p className="text-xs text-muted-foreground">{e.published?'Publicado':'Rascunho'}</p></div><div className="flex"><Button variant="ghost" size="icon" onClick={()=>setEditing(e)}><Edit3/></Button><Button variant="ghost" size="icon" onClick={async()=>{if(confirm('Excluir este episódio?')){await del({data:{id:e.id}});await refresh()}}}><Trash2/></Button></div></div>)}</div></section>}

