import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { ArrowDown, ArrowUpRight, Building2, HeartHandshake, Leaf, Send, type LucideIcon } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { SiteLayout } from "@/components/site/Layout";
import { Reveal } from "@/components/site/Reveal";
import { ImmersivePlayer, type Episode } from "@/components/site/ImmersivePlayer";
import { getPublicContent, sendContact } from "@/lib/content.functions";
import hero from "@/assets/viviane-hero.jpg";
import portrait from "@/assets/viviane-portrait.jpg";
import podcastCover from "@/assets/podcast-cover.jpg";
import articlePath from "@/assets/article-path.jpg";
import articleCareer from "@/assets/article-career.jpg";
import articleConnection from "@/assets/article-connection.jpg";

const pathways: Array<{ icon: LucideIcon; title: string; text: string; cta: string }> = [
  { icon: Leaf, title: "Para Grupos", text: "Jornadas e grupos terapêuticos para quem quer se desenvolver junto com outras pessoas — porque há descobertas que só acontecem no encontro.", cta: "Conheça as jornadas" },
  { icon: HeartHandshake, title: "Para Pessoas", text: "Psicoterapia, desenvolvimento de carreira e orientação vocacional para compreender sua história, fortalecer sua autonomia e construir escolhas alinhadas.", cta: "Saiba mais" },
  { icon: Building2, title: "Para Empresas", text: "Palestras, treinamentos e projetos de desenvolvimento humano, construídos por quem viveu mais de 20 anos dentro das organizações.", cta: "Conheça as soluções" },
];

export const Route = createFileRoute("/")({
  loader: () => getPublicContent(),
  head: () => ({ meta: [{ title: "Viviane Brito — Psicologia e Desenvolvimento" },{ name:"description", content:"Psicologia, carreira e desenvolvimento humano com Viviane Brito."},{ property:"og:title", content:"Viviane Brito — Psicologia e Desenvolvimento"},{ property:"og:description", content:"Compreender a história. Ampliar o olhar. Construir novos caminhos."},{ property:"og:type", content:"website"},{ name:"twitter:card", content:"summary_large_image" }] }), component: Home,
});
function Home() { const data = Route.useLoaderData(); const send = useServerFn(sendContact); const [sent,setSent]=useState(false); const [player,setPlayer]=useState<Episode|null>(null); const featured=data.episodes[0];
const articleImages=[articlePath,articleCareer,articleConnection]; const articleFallback=["Toda mudança começa quando escutamos o que a nossa história quer dizer.","Escolher um novo caminho também é uma forma de voltar para si.","Há encontros que ampliam o olhar e transformam possibilidades."];
return <SiteLayout><section className="relative min-h-[94svh] overflow-hidden bg-primary text-primary-foreground"><img src={hero} alt="Mulher contemplando uma paisagem aberta" width={1536} height={1024} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-hero-overlay"/><div className="relative mx-auto flex min-h-[94svh] max-w-7xl flex-col justify-end px-6 pb-14 pt-32"><p className="eyebrow mb-5">Psicologia e desenvolvimento humano</p><h1 className="max-w-5xl font-display text-[clamp(3.1rem,7.2vw,7.6rem)] leading-[.9]">Toda pessoa carrega uma história que merece ser compreendida.</h1><div className="mt-7 grid gap-7 md:grid-cols-[1fr_auto] md:items-end"><p className="max-w-xl text-base leading-7 text-primary-foreground/80">Compreender a história. Ampliar o olhar. Construir novos caminhos. Há mais de 20 anos acompanhando pessoas, grupos e organizações.</p><div className="flex flex-wrap gap-3"><a href="#caminhos"><Button variant="secondary" size="lg">Conheça os caminhos</Button></a><a href="#contato"><Button variant="outline" size="lg" className="border-primary-foreground/40 bg-transparent text-primary-foreground hover:bg-primary-foreground hover:text-primary">Vamos conversar</Button></a></div></div><ArrowDown className="mt-8 h-5 w-5 animate-bounce"/></div></section>
<section className="section"><Reveal><p className="eyebrow text-primary">Bem-vindo</p><div className="editorial-grid mt-8"><h2 className="section-title">Talvez você tenha chegado até aqui porque está vivendo um momento de mudança.</h2><div className="space-y-5 text-lg leading-8 text-muted-foreground"><p>Uma transição profissional. Uma escolha importante. Um desafio em seus relacionamentos.</p><p>Ou simplesmente porque sente que chegou a hora de olhar para si com mais profundidade.</p><p className="text-foreground">Toda pessoa carrega recursos que nem sempre consegue reconhecer sozinha. Meu trabalho é ajudar você a encontrá-los.</p><p className="font-display text-3xl text-primary">Que bom ter você aqui.</p></div></div></Reveal></section>
<section id="caminhos" className="section bg-secondary"><Reveal><p className="eyebrow text-primary">Como podemos caminhar juntos</p><h2 className="section-title mt-6 max-w-4xl">Caminhos singulares para diferentes momentos da vida.</h2></Reveal><div className="mt-16 grid gap-px overflow-hidden rounded-lg border bg-border md:grid-cols-3">{pathways.map(({ icon: Icon, title, text, cta },i)=><Reveal key={title} className="h-full"><article className="group flex h-full min-h-[430px] flex-col bg-background p-8 transition-colors hover:bg-primary hover:text-primary-foreground md:p-10"><span className="mb-20 text-sm opacity-60">0{i+1}</span><Icon className="mb-5 h-8 w-8"/><h3 className="font-display text-4xl">{title}</h3><p className="mt-5 leading-7 opacity-70">{text}</p><span className="mt-auto flex items-center gap-2 pt-8 text-sm font-medium">{cta} <ArrowUpRight className="h-4 w-4"/></span></article></Reveal>)}</div></section>
<section className="section"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><Reveal><img src={portrait} alt="Retrato editorial representando Viviane Brito" loading="lazy" width={1280} height={1600} className="aspect-[4/5] w-full rounded-lg object-cover"/></Reveal><Reveal><p className="eyebrow text-primary">Quem é Viviane Brito?</p><h2 className="section-title mt-6">Apaixonada por pessoas e pelas possibilidades de transformação.</h2><div className="mt-7 space-y-5 text-lg leading-8 text-muted-foreground"><p>Sou psicóloga, psicoterapeuta integrativa transpessoal, consultora de carreira e facilitadora sistêmica.</p><p>Minha caminhada começou dentro das organizações, onde por mais de duas décadas acompanhei pessoas, equipes e lideranças. Hoje, esse caminho se expandiu para a clínica, os grupos e os projetos de desenvolvimento humano.</p><p className="font-display text-3xl text-primary">Acredito que toda pessoa é muito maior do que qualquer momento que esteja vivendo.</p></div><Link to="/about" className="mt-8 inline-flex items-center gap-2 font-medium text-primary">Conheça minha história <ArrowUpRight className="h-4 w-4"/></Link></Reveal></div></section>
<section className="section bg-primary text-primary-foreground"><Reveal><p className="eyebrow opacity-70">Minha forma de trabalhar</p><h2 className="section-title mt-6 max-w-4xl">Três movimentos para transformar presença em escolha.</h2></Reveal><div className="mt-16 divide-y divide-primary-foreground/20">{[["01","Compreender a história","Toda transformação começa quando compreendemos nossa trajetória com respeito e profundidade."],["02","Ampliar o olhar","Novas possibilidades surgem quando enxergamos além daquilo que sempre acreditamos sobre nós mesmos."],["03","Construir novos caminhos","Com mais consciência, fazemos escolhas mais livres e construímos uma vida mais coerente com quem somos."]].map(x=><Reveal key={x[0]}><div className="grid gap-6 py-9 md:grid-cols-[80px_1fr_1fr]"><span className="opacity-50">{x[0]}</span><h3 className="font-display text-4xl">{x[1]}</h3><p className="leading-7 opacity-70">{x[2]}</p></div></Reveal>)}</div></section>
<section className="section"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><Reveal><p className="eyebrow text-primary">Alma e Caminhos — O Podcast</p><h2 className="section-title mt-6">A jornada entre vida, propósito e carreira.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">O Alma e Caminhos nasceu do desejo de levar para além do consultório conversas sobre desenvolvimento humano, propósito e carreira.</p><div className="mt-8 flex gap-3">{featured && <Button size="lg" onClick={()=>setPlayer({ ...featured, cover_url: featured.cover_url || podcastCover })}>Ouça o podcast</Button>}<Link to="/podcasts"><Button variant="outline" size="lg">Ver episódios</Button></Link></div></Reveal><Reveal><button onClick={()=>featured&&setPlayer({ ...featured, cover_url: featured.cover_url || podcastCover })} className="group relative w-full overflow-hidden rounded-lg text-left" aria-label="Ouvir Alma e Caminhos"><img src={featured?.cover_url || podcastCover} alt="Capa do podcast Alma e Caminhos" loading="lazy" width={1280} height={1280} className="aspect-square w-full object-cover transition-transform duration-700 group-hover:scale-105"/><span className="absolute bottom-5 left-5 rounded-full bg-background px-5 py-3 text-sm text-foreground shadow-lg">Ouvir agora</span></button></Reveal></div></section>
<section id="artigos" className="section bg-secondary"><Reveal className="text-center"><span className="inline-flex rounded-full bg-background px-4 py-2 text-xs font-medium">+ Palavras para ampliar o olhar</span><h2 className="section-title mx-auto mt-20 max-w-3xl">Artigos, palavras e reflexões</h2><Link to="/articles" className="mt-12 inline-flex rounded-full bg-primary px-5 py-2.5 text-sm text-primary-foreground">Ler todos</Link></Reveal><div className="mt-12 grid gap-2 md:grid-cols-3">{articleImages.map((image,i)=>{const article=data.articles[i];const title=article?.title||articleFallback[i];const card=<article className="group relative min-h-[460px] overflow-hidden rounded-lg"><img src={article?.cover_url||image} alt="" loading="lazy" width={1200} height={1504} className="absolute inset-0 size-full object-cover transition-transform duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-article-overlay"/><div className="absolute inset-x-0 bottom-0 p-7 text-primary-foreground"><span className="text-7xl leading-none">“</span><h3 className="-mt-4 font-display text-3xl leading-tight">{title}</h3><p className="mt-7 text-xs uppercase">{(article?.article_categories as {name?:string}|null)?.name||"Texto reflexivo"}</p></div></article>;return article?<Link key={article.id} to="/articles/$slug" params={{slug:article.slug}}>{card}</Link>:<div key={title}>{card}</div>})}</div></section>
<section className="section"><Reveal className="text-center"><span className="inline-flex rounded-full bg-secondary px-4 py-2 text-xs font-medium">+ Depoimentos</span><h2 className="section-title mx-auto mt-20 max-w-4xl">Histórias reais de quem escolheu construir novos caminhos</h2><span className="mt-12 inline-flex rounded-full bg-primary px-5 py-2.5 text-sm text-primary-foreground">Relatos de encontros</span></Reveal><div className="mt-12 overflow-hidden rounded-lg border bg-secondary"><div className="grid lg:grid-cols-2"><img src={articleConnection} alt="Duas mulheres conversando durante uma caminhada" loading="lazy" width={1200} height={1504} className="h-full min-h-[420px] w-full object-cover"/><blockquote className="flex min-h-[420px] flex-col justify-between p-8 md:p-12"><div><span className="text-7xl leading-none text-primary">“</span><p className="mt-4 font-display text-4xl leading-tight">Depoimento não clínico a preencher.</p><p className="mt-7 max-w-lg leading-7 text-muted-foreground">Este espaço receberá relatos reais sobre palestras, grupos e processos de desenvolvimento.</p></div><footer className="mt-10 text-sm">Nome · Contexto do trabalho</footer></blockquote></div></div><div className="mt-2 grid gap-2 md:grid-cols-2">{[articlePath,articleCareer].map((image,i)=><blockquote key={image} className="relative min-h-[430px] overflow-hidden rounded-lg text-primary-foreground"><img src={image} alt="" loading="lazy" width={1200} height={1504} className="absolute inset-0 size-full object-cover"/><div className="absolute inset-0 bg-article-overlay"/><div className="absolute inset-x-0 bottom-0 p-8"><span className="text-6xl leading-none">“</span><p className="font-display text-3xl">Depoimento não clínico a preencher.</p><footer className="mt-8 text-sm">Nome {i+1} · Contexto do trabalho</footer></div></blockquote>)}</div></section>
<section id="contato" className="section"><div className="grid gap-12 lg:grid-cols-2"><Reveal><p className="eyebrow text-primary">Vamos conversar?</p><h2 className="section-title mt-6">Se chegou o momento de olhar para sua história com mais carinho, será um prazer caminhar ao seu lado.</h2><p className="mt-6 text-muted-foreground">WhatsApp: a preencher · Prazo de resposta: a preencher</p></Reveal><Reveal><form className="grid gap-4" onSubmit={async e=>{e.preventDefault(); const f=new FormData(e.currentTarget); await send({data:{name:String(f.get('name')),email:String(f.get('email')),phone:String(f.get('phone')||''),message:String(f.get('message'))}}); setSent(true); e.currentTarget.reset();}}><input name="name" required placeholder="Seu nome" className="field"/><input name="email" type="email" required placeholder="Seu e-mail" className="field"/><input name="phone" placeholder="Seu telefone (opcional)" className="field"/><textarea name="message" required minLength={10} rows={5} placeholder="Como posso ajudar?" className="field resize-none"/>{sent&&<p className="text-sm text-primary">Mensagem enviada. Obrigada pelo contato.</p>}<Button type="submit" size="lg" className="justify-between">Enviar mensagem <Send/></Button></form></Reveal></div></section>{player&&<ImmersivePlayer episode={player} onClose={()=>setPlayer(null)}/>}</SiteLayout>}
