import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, ArrowUpRight, Building2, HeartHandshake, Leaf, MessageCircle, Play, type LucideIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteLayout } from "@/components/site/Layout";
import { Reveal } from "@/components/site/Reveal";
import { usePodcastPlayer } from "@/components/site/PodcastPlayer";
import { useWhatsApp } from "@/components/site/WhatsAppDialog";
import { getPublicContent } from "@/lib/content.functions";
import heroAsset from "@/assets/hero-field.png.asset.json";
const hero = heroAsset.url;
import portraitAsset from "@/assets/viviane-portrait.png.asset.json";
const portrait = portraitAsset.url;
import podcastCover from "@/assets/podcast-cover.jpg";
import articlePath from "@/assets/article-path.jpg";
import articleCareer from "@/assets/article-career.jpg";
import articleConnection from "@/assets/article-connection.jpg";

const pathways: Array<{ icon: LucideIcon; slug: string; title: string; text: string; cta: string }> = [
  { icon: Leaf, slug: "grupos", title: "Para Grupos", text: "Jornadas e grupos terapêuticos para quem quer se desenvolver junto com outras pessoas — porque há descobertas que só acontecem no encontro.", cta: "Conheça as jornadas" },
  { icon: HeartHandshake, slug: "pessoas", title: "Para Pessoas", text: "Psicoterapia, desenvolvimento de carreira e orientação vocacional para compreender sua história, fortalecer sua autonomia e construir escolhas alinhadas.", cta: "Saiba mais" },
  { icon: Building2, slug: "empresas", title: "Para Empresas", text: "Palestras, treinamentos e projetos de desenvolvimento humano, construídos por quem viveu mais de 20 anos dentro das organizações.", cta: "Conheça as soluções" },
];


export const Route = createFileRoute("/")({
  loader: () => getPublicContent(),
  head: () => ({ meta: [{ title: "Viviane Brito — Psicologia e Desenvolvimento" },{ name:"description", content:"Psicologia, carreira e desenvolvimento humano com Viviane Brito."},{ property:"og:title", content:"Viviane Brito — Psicologia e Desenvolvimento"},{ property:"og:description", content:"Compreender a história. Ampliar o olhar. Construir novos caminhos."},{ property:"og:type", content:"website"},{ name:"twitter:card", content:"summary_large_image" }] }), component: Home,
});
function Home() { const data = Route.useLoaderData(); const { openWhatsApp } = useWhatsApp(); const {playEpisode}=usePodcastPlayer(); const featured=data.episodes[0];
const articleImages=[articlePath,articleCareer,articleConnection]; const articleFallback=["Toda mudança começa quando escutamos o que a nossa história quer dizer.","Escolher um novo caminho também é uma forma de voltar para si.","Há encontros que ampliam o olhar e transformam possibilidades."];
 return <SiteLayout><section className="home-hero relative overflow-hidden bg-primary text-primary-foreground"><img src={hero} alt="Mulher contemplando uma paisagem aberta" width={1536} height={1024} className="absolute inset-0 h-full w-full object-cover saturate-[.7]"/><div className="absolute inset-0 bg-hero-overlay"/><div className="relative mx-auto flex min-h-[100svh] max-w-7xl flex-col justify-end px-6 pb-10 pt-32"><p className="hero-pill mb-5">✦ Psicologia e desenvolvimento humano</p><h1 className="max-w-4xl font-display text-[clamp(3.25rem,6.4vw,6.9rem)] leading-[.96]">Toda pessoa carrega uma história que merece ser compreendida.</h1><p className="mt-7 max-w-lg text-sm leading-6 text-primary-foreground/80">Compreender a história. Ampliar o olhar. Construir novos caminhos. Há mais de 20 anos acompanhando pessoas, grupos e organizações.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#caminhos"><Button variant="secondary" className="rounded-full">Conheça os caminhos</Button></a><Button variant="ghost" onClick={openWhatsApp} className="rounded-full text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground">Vamos conversar</Button></div><ArrowDown className="mt-8 h-5 w-5 animate-bounce"/></div></section>
 <div className="marquee" aria-label="Áreas de atuação"><div className="marquee-track">{["Psicoterapia","Desenvolvimento de carreira","Orientação vocacional","Grupos terapêuticos","Desenvolvimento humano","Psicoterapia","Desenvolvimento de carreira","Orientação vocacional"].map((item,i)=><span key={`${item}-${i}`}>✦ {item}</span>)}</div></div>
 <section className="section"><Reveal><div className="philosophy-heading"><p className="eyebrow text-primary">Bem-vindo</p><h2 className="section-title text-center">Talvez você tenha chegado até aqui porque está vivendo um momento de mudança.</h2></div></Reveal><Reveal className="assemble mt-16 grid gap-px overflow-hidden rounded-[2rem] bg-border md:grid-cols-3"><article className="min-h-72 bg-secondary p-8"><span className="text-sm opacity-50">01</span><p className="mt-20 font-display text-3xl">Uma transição profissional.</p></article><article className="min-h-72 bg-primary p-8 text-primary-foreground"><span className="text-sm opacity-60">02</span><p className="mt-20 font-display text-3xl">Uma escolha importante.</p></article><article className="min-h-72 bg-background p-8"><span className="text-sm opacity-50">03</span><p className="mt-20 font-display text-3xl">Um novo olhar para si.</p></article></Reveal><Reveal className="assemble editorial-grid mt-14"><p className="font-display text-4xl text-primary">Que bom ter você aqui.</p><div className="space-y-5 text-lg leading-8 text-muted-foreground"><p>Ou simplesmente porque sente que chegou a hora de olhar para si com mais profundidade.</p><p className="text-foreground">Toda pessoa carrega recursos que nem sempre consegue reconhecer sozinha. Meu trabalho é ajudar você a encontrá-los.</p></div></Reveal></section>
<section id="caminhos" className="section bg-secondary"><Reveal><p className="eyebrow text-primary">Como podemos caminhar juntos</p><h2 className="section-title mt-6 max-w-4xl">Caminhos singulares para diferentes momentos da vida.</h2></Reveal><Reveal className="assemble mt-16 grid gap-px overflow-hidden rounded-lg border bg-border md:grid-cols-3">{pathways.map(({ icon: Icon, slug, title, text, cta },i)=><Link key={title} to="/servicos/$slug" params={{slug}} className="group flex h-full min-h-[430px] flex-col bg-background p-8 transition-colors hover:bg-primary hover:text-primary-foreground md:p-10"><span className="mb-20 text-sm opacity-60">0{i+1}</span><Icon className="mb-5 h-8 w-8"/><h3 className="font-display text-4xl">{title}</h3><p className="mt-5 leading-7 opacity-70">{text}</p><span className="mt-auto flex items-center gap-2 pt-8 text-sm font-medium">{cta} <ArrowUpRight className="h-4 w-4"/></span></Link>)}</Reveal></section>
<section className="section"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><Reveal><img src={portrait} alt="Retrato editorial representando Viviane Brito" loading="lazy" width={1280} height={1600} className="aspect-[4/5] w-full rounded-lg object-cover"/></Reveal><Reveal><p className="eyebrow text-primary">Quem é Viviane Brito?</p><h2 className="section-title mt-6">Apaixonada por pessoas e pelas possibilidades de transformação.</h2><div className="mt-7 space-y-5 text-lg leading-8 text-muted-foreground"><p>Sou psicóloga, psicoterapeuta integrativa transpessoal, consultora de carreira e facilitadora sistêmica.</p><p>Minha caminhada começou dentro das organizações, onde por mais de duas décadas acompanhei pessoas, equipes e lideranças. Hoje, esse caminho se expandiu para a clínica, os grupos e os projetos de desenvolvimento humano.</p><p className="font-display text-3xl text-primary">Acredito que toda pessoa é muito maior do que qualquer momento que esteja vivendo.</p></div><Link to="/about" className="mt-8 inline-flex items-center gap-2 font-medium text-primary">Conheça minha história <ArrowUpRight className="h-4 w-4"/></Link></Reveal></div></section>
<section className="section bg-primary text-primary-foreground"><Reveal><p className="eyebrow opacity-70">Minha forma de trabalhar</p><h2 className="section-title mt-6 max-w-4xl">Três movimentos para transformar presença em escolha.</h2></Reveal><div className="mt-16 divide-y divide-primary-foreground/20">{[["01","Compreender a história","Toda transformação começa quando compreendemos nossa trajetória com respeito e profundidade."],["02","Ampliar o olhar","Novas possibilidades surgem quando enxergamos além daquilo que sempre acreditamos sobre nós mesmos."],["03","Construir novos caminhos","Com mais consciência, fazemos escolhas mais livres e construímos uma vida mais coerente com quem somos."]].map(x=><Reveal key={x[0]}><div className="grid gap-6 py-9 md:grid-cols-[80px_1fr_1fr]"><span className="opacity-50">{x[0]}</span><h3 className="font-display text-4xl">{x[1]}</h3><p className="leading-7 opacity-70">{x[2]}</p></div></Reveal>)}</div></section>
 <section className="section"><Reveal><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><p className="eyebrow text-primary">Alma e Caminhos — O Podcast</p><h2 className="section-title mt-6">A jornada entre vida, propósito e carreira.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Conversas sobre desenvolvimento humano, propósito e carreira para ouvir no seu tempo.</p></div>{featured&&<button onClick={()=>playEpisode({...featured,cover_url:featured.cover_url||podcastCover})} className="podcast-feature"><img src={featured.cover_url||podcastCover} alt={`Capa de ${featured.title}`} className="h-28 w-28 shrink-0 rounded-2xl object-cover md:h-36 md:w-36"/><div className="min-w-0 text-left"><p className="eyebrow opacity-60">Episódio em destaque</p><h3 className="mt-2 font-display text-3xl">{featured.title}</h3><span className="mt-5 inline-flex items-center gap-2 text-sm font-medium"><Play className="size-4"/> Reproduzir</span></div></button>}</div><div className="mt-10 divide-y divide-border border-y border-border">{data.episodes.slice(0,4).map((episode,i)=><button key={episode.id} onClick={()=>playEpisode({...episode,cover_url:episode.cover_url||podcastCover})} className="episode-row"><span className="text-sm opacity-50">{String(i+1).padStart(2,"0")}</span><img src={episode.cover_url||podcastCover} alt="" className="size-14 rounded-lg object-cover"/><span className="min-w-0 flex-1 truncate text-left font-medium">{episode.title}</span><span className="grid size-10 place-items-center rounded-full bg-primary text-primary-foreground"><Play className="size-4"/></span></button>)}</div><Link to="/podcasts" className="mt-8 inline-flex rounded-full border border-border px-5 py-2.5 text-sm">Ver todos os episódios</Link></Reveal></section>
<section id="artigos" className="section bg-secondary"><Reveal className="text-center"><span className="inline-flex rounded-full bg-background px-4 py-2 text-xs font-medium">+ Palavras para ampliar o olhar</span><h2 className="section-title mx-auto mt-20 max-w-3xl">Artigos, palavras e reflexões</h2><Link to="/articles" className="mt-12 inline-flex rounded-full bg-primary px-5 py-2.5 text-sm text-primary-foreground">Ler todos</Link></Reveal><Reveal className="assemble mt-12 grid gap-2 md:grid-cols-3">{articleImages.map((image,i)=>{const article=data.articles[i];const title=article?.title||articleFallback[i];const card=<article className="relative min-h-[460px] overflow-hidden rounded-lg"><img src={article?.cover_url||image} alt="" loading="lazy" width={1200} height={1504} className="media-card-image absolute inset-0 size-full object-cover"/><div className="absolute inset-0 bg-article-overlay"/><div className="absolute inset-x-0 bottom-0 p-7 text-primary-foreground"><span className="text-7xl leading-none">“</span><h3 className="-mt-4 font-display text-3xl leading-tight">{title}</h3><p className="mt-7 text-xs uppercase">{(article?.article_categories as {name?:string}|null)?.name||"Texto reflexivo"}</p></div></article>;return article?<Link key={article.id} to="/articles/$slug" params={{slug:article.slug}} className="testimonial-card media-card block">{card}</Link>:<div key={title} className="testimonial-card media-card">{card}</div>})}</Reveal></section>
<section id="depoimentos" className="section"><Reveal className="text-center"><span className="inline-flex rounded-full bg-secondary px-4 py-2 text-xs font-medium">+ Depoimentos</span><h2 className="section-title mx-auto mt-20 max-w-4xl">Histórias reais de quem escolheu construir novos caminhos</h2><Link to="/depoimentos" className="mt-12 inline-flex rounded-full bg-primary px-5 py-2.5 text-sm text-primary-foreground">Relatos de encontros</Link></Reveal><Reveal className="assemble mt-12 grid gap-2 md:grid-cols-2">{(data.testimonials.length?data.testimonials:[]).map((t,i)=><Link key={t.id} to="/depoimentos/$slug" params={{slug:t.slug}} className={`testimonial-card media-card relative block min-h-[430px] overflow-hidden rounded-lg text-primary-foreground ${i===0?"md:col-span-2 md:min-h-[480px]":""}`}><img src={t.cover_url||[articleConnection,articlePath,articleCareer][i%3]} alt="" loading="lazy" className="media-card-image absolute inset-0 size-full object-cover"/><div className="absolute inset-0 bg-article-overlay"/><blockquote className="absolute inset-x-0 bottom-0 p-8 md:p-10"><span className="text-6xl leading-none">“</span><p className="-mt-3 max-w-2xl font-display text-3xl leading-tight md:text-4xl">{t.quote||"Depoimento não clínico a preencher."}</p><footer className="mt-7 text-sm">{t.name}{t.context&&` · ${t.context}`}</footer><span className="testimonial-more mt-4 inline-flex text-sm font-medium">Ler o depoimento completo →</span></blockquote></Link>)}</Reveal>{!data.testimonials.length&&<div className="empty-state mt-12"><p className="font-display text-4xl">Os depoimentos estão sendo preparados.</p></div>}</section>
 <section id="contato" className="section"><Reveal><div className="mx-auto max-w-3xl text-center"><p className="eyebrow text-primary">Vamos conversar?</p><h2 className="section-title mt-6">Se chegou o momento de olhar para sua história com mais carinho, será um prazer caminhar ao seu lado.</h2><p className="mt-6 text-muted-foreground">Atendimento pelo WhatsApp · +55 11 93344-1809</p><Button size="lg" onClick={openWhatsApp} className="mt-8 rounded-full"><MessageCircle className="size-4"/> Vamos Conversar</Button></div></Reveal></section></SiteLayout>}
